### ISSUE TITLE
AttributeError: 'API' object has no attribute 'configuration'

### ISSUE THREAD

**Issue by aswin1447** [fxcoudert/PapersBot#9]
full error log

Traceback (most recent call last):
  File "papersbot.py", line 362, in <module>
    main()
  File "papersbot.py", line 350, in main
    bot = PapersBot(doTweet)
  File "papersbot.py", line 228, in __init__
    twconfig = getTwitterConfig(self.api)
  File "papersbot.py", line 161, in getTwitterConfig
    config = api.configuration()
AttributeError: 'API' object has no attribute 'configuration'

**Comment by fxcoudert** [comment]
The code was updated with a fix: 
https://github.com/fxcoudert/PapersBot/commit/2d59d26369dd677cd50935b21b0819be8c355c4c
